name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    name: "Build Docker Container" # step 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # step 1
      
      - name: setup GO # step 2
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: create env file # step 3
        env:
          APP_PORT: ${{ secrets.APP_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          touch .env
          echo APP_PORT=$APP_PORT >> .env
          echo DB_USER=$DB_USER >> .env
          echo DB_PASS=$DB_PASS >> .env
          echo DB_HOST=$DB_HOST >> .env
          echo DB_PORT=$DB_PORT >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build docker container
        run: make build-image
      
      - name: push docker container
        run: make push-image
  
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      
      - name: Deploy to Server EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_EMPLOYEE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS_EMPLOYEE }}
          REMOTE_USER: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} '
            #Now we have got the access of EC2 and we will start the deploy .
            sudo chmod 777 /var/run/docker.sock
            sudo docker pull azkafr92/employee-service:latest &&
            sudo docker container stop employee-service || true &&
            sudo docker container rm employee-service || true &&
            sudo docker container create --name employee-service -p 80:8080 azkafr92/employee-service:latest &&
            sudo docker container start employee-service
          '